# From https://github.com/softprops/action-gh-release

# Need to change the text for the release description

# Commit changes, and then add a tag

# Can push and add a tag using: 
# git tag tag_name (eg v1.0.0)
# git push origin main tag_name

# Use this to delete local tags (tag deleted on the website side)
# git tag -d tag_name

name: auto-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
              Changes in this Release
              - Formal Documentation added.
              - Updated requirements to be more specific.
              - Bug Fixes.